"""bake_pfdbox.py OUT.js BOOK.json [BOOK.json ...] — merge extracted box books into data/pfdbox.js (PFDBOX).

Run from the repo root:  python3 tools/pfd-boxbook/bake_pfdbox.py data/pfdbox.js work/book_e01.json work/book_e05.json
Boxes from every book; a box number seen in two books is an error. Hydrants from every book, merged across
books within 2 m (neighbouring books overlap at their edges). Everything is lat/lon, 6 decimals (~0.1 m);
index.html projects it with ll2world at load.
"""
import json, math, sys

KX = 110540*math.cos(math.radians(39.95))
f6 = lambda v: ('%.6f' % v).rstrip('0').rstrip('.')
pt = lambda p: '['+f6(p[0])+','+f6(p[1])+']'


def main(out, books):
    boxes = {}; hyd = []; srcs = []
    for path in books:
        B = json.load(open(path))
        srcs.append('E%02d' % B['engine'])
        for n, b in B['boxes'].items():
            assert n not in boxes, f'box {n} is in two books'
            boxes[n] = (B['engine'], b['ring'])
        hyd += [tuple(h[:2]) for h in B['hydrants']]
    grid = {}; H = []
    for h in sorted(hyd):
        gx, gy = int(h[0]*1e4), int(h[1]*1e4)
        if any(math.hypot((h[0]-o[0])*110540, (h[1]-o[1])*KX) < 2.0 for a in (gx-1, gx, gx+1) for b in (gy-1, gy, gy+1) for o in grid.get((a, b), [])):
            continue
        H.append(h); grid.setdefault((gx, gy), []).append(h)
    L = ['const PFDBOX = {',
         '// PFD box maps: real box polygons and hydrants lifted from the Philadelphia Fire Department GIS map books',
         '// "Exx Box Breakdown" (map credit: Philadelphia Fire Department; PFDGIS@phila.gov). Books: ' + ', '.join(srcs) + '.',
         '// The books are GeoPDFs: every page carries its own georeference (NAD83 PA South ft, corner lat/lon), and the',
         "// Response_Zones and Hydrants layers are vector, so these are the map's own coordinates, not traces.",
         "// boxes: each box polygon from its own page (the one closed ring around that page's label), [lat,lon], ring",
         '//   not closed. hyd: every hydrant marker on any page (incl. the fringes of neighbouring companies), de-duplicated',
         '//   across pages and books. Generated by tools/pfd-boxbook (see its README) - re-bake, do not hand-edit.',
         'src: "PFD GIS box breakdown books: ' + ', '.join(srcs) + '",',
         'boxes: [']
    for n in sorted(boxes):
        e, r = boxes[n]
        L.append('{b:"%s",e:%d,ring:[%s]},' % (n, e, ','.join(pt(p) for p in r[:-1])))
    L += ['],', 'hyd: [']
    for i in range(0, len(H), 12):
        L.append(','.join(pt(p) for p in H[i:i+12])+',')
    L += [']', '};']
    open(out, 'w').write('\n'.join(L)+'\n')
    print(f'{out}: {len(boxes)} boxes from {", ".join(srcs)}, {len(H)} hydrants, longest line {max(map(len, L))}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2:])
